language: java
sudo: false
jdk:
    - openjdk8
    - openjdk11
stages:
  - name: script
    # require the branch name to be master (note for PRs this is the base branch name)
    if: $TRAVIS_EVENT_TYPE != cron
before_install:
- cp settings.xml $HOME/.m2/settings.xml
install: mvn -P core-release install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn -P core-release,arquillian-tests test -B
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: script
  script: "mvn -P dev deploy -q"
  skip_cleanup: true
  on:
    condition: $TRAVIS_EVENT_TYPE = cron
    jdk: openjdk8
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ada7bbc05b2a99cff40
    on_success: change
    on_failure: always
    on_start: never
